DROP TABLE IF EXISTS FLIGHTSCHEDULE;
  
CREATE TABLE FLIGHTSCHEDULE (
  SOURCE VARCHAR(250),
  DESTINATION VARCHAR(250) NOT NULL,
  DATE VARCHAR(250) NOT NULL,	
  FLIGHT_ID VARCHAR(250) NOT NULL,
  FLIGHT_NAME VARCHAR(250) NOT NULL
);